using System.Diagnostics;
using System.Data.SqlClient;
using System.Data;

namespace UWPWeather
{
    class DatabaseHelper
    {

        //public void Database()
        //{
        //    SqlConnection cn = new SqlConnection();
        //    DataSet CustomersDataSet = new DataSet();
        //    SqlDataAdapter da;
        //    SqlCommandBuilder cmdBuilder;

        //    //cn.ConnectionString = "Server=server;Database=AddressBook;UID=sa;PWD=nhti;";
        //    cn.ConnectionString = "Data Source=localhost;Initial Catalog=Weather;Integrated Security=True";
        //    cn.Open();

        //    da = new SqlDataAdapter("SELECT * FROM dbo.Data", cn);

        //    //the UpdateCommand, InsertCommand, and DeleteCommand properties of the SqlDataAdapter.
        //    cmdBuilder = new SqlCommandBuilder(da);

        //    //Populate the DataSet by running the Fill method of the SqlDataAdapter.
        //    da.Fill(CustomersDataSet, "Data");

        //    //Display the Update, Insert, and Delete commands that were automatically generated
        //    //by the SqlCommandBuilder object.
        //    Debug.WriteLine("Update command Generated by the Command Builder : ");
        //    Debug.WriteLine("==================================================");
        //    Debug.WriteLine(cmdBuilder.GetUpdateCommand().CommandText);
        //    Debug.WriteLine("         ");

        //    Debug.WriteLine("Insert command Generated by the Command Builder : ");
        //    Debug.WriteLine("==================================================");
        //    Debug.WriteLine(cmdBuilder.GetInsertCommand().CommandText);
        //    Debug.WriteLine("         ");

        //    Debug.WriteLine("Delete command Generated by the Command Builder : ");
        //    Debug.WriteLine("==================================================");
        //    Debug.WriteLine(cmdBuilder.GetDeleteCommand().CommandText);
        //    Debug.WriteLine("         ");

        //    //Write out the value in the CustName field before updating the data using the DataSet.
        //    Debug.WriteLine("Customer Name before Update : " + CustomersDataSet.Tables["Data"].Rows[0]["Temperature"]);

        //    //Modify the value of the CustName field.
        //    CustomersDataSet.Tables["Data"].Rows[0]["Temperature"] = 45;

        //    //Post the data modification to the database.
        //    da.Update(CustomersDataSet, "Data");

        //    Debug.WriteLine("Customer Name updated successfully");

        //    //Close the database connection.
        //    cn.Close();
        }
    }
}
